### PR TITLE
Bump OMERO version to 5.3.5

### PR DESCRIPTION
**Pull request by sbesson**
Following http://www.openmicroscopy.org/2017/10/04/omero-5-3-5.html

### CODE REVIEW

**Comment by sbesson** [comment]
Merging and deploying for consumption in the downstream projects.

**Comment by sbesson** [comment]
While bumping https://github.com/ome/minimal-omero-client and trying to simplify the `repositories`, I got some errors similar to what @jburel was highlighting in https://github.com/ome/pom-omero-client/pull/25#issuecomment-302542638. Looking at the detail of the `pom`, I think I identified why I could not reproduce in https://github.com/ome/pom-omero-client/pull/25#issuecomment-302550021. Our Virtual Maven repository in the OME Artifactory is currently configured to discard the repositories references - see https://www.jfrog.com/confluence/display/RTF/Virtual+Repositories#VirtualRepositories-Maven,Gradle,IvyandSBTRepositories.

The `pom-omero-client-5.3.5.pom` retrieved from https://artifacts.openmicroscopy.org/artifactory/maven/ has no `repositories` element. For minimal-omeor-client 5.3.5, it might be more conservative to only bump the parent POM version as the POM is already published and others might already have consumed it locally. For OMERO 5.4.0 or later, we could consider switching the policy to not removing any repository reference in POMs.

**Comment by joshmoore** [comment]
@sbesson: did the change get captured somewhere as a card?

**Comment by sbesson** [comment]
Not yet. I was largely waiting on your return to have the discussion first. As the 5.4.0 pom hasn't been published yet, I can see 2 options:
- either we are happy with the change above and we apply it before publishing pom-omero-client 5.4.0 (and simplify the client repos)
- or we defer this to a later version in which case I can create an OMERO 5.x card

**Comment by sbesson** [comment]
Captured as https://trello.com/c/1lDDFmDk/284-artifactory-configuration-change given that we published pom-omero-client:5.4.0 - https://github.com/ome/pom-omero-client/pull/31.

**Pull request merged**
